# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_group', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('you1', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others1', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you2', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others2', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you3', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others3', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you4', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others4', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you5', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others5', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you6', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others6', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you7', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others7', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you8', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others8', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you9', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others9', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you10', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others10', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you11', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others11', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you12', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others12', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you13', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others13', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you14', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others14', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('you15', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('others15', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('random_order1', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order2', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order3', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order4', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order5', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order6', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order7', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order8', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order9', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order10', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order11', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order12', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order13', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order14', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order15', otree.db.models.IntegerField(default=-1, null=True)),
                ('svo_angle', otree.db.models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('svo_type', otree.db.models.StringField(choices=[('Altruist', 'Altruist'), ('Prosocial', 'Prosocial'), ('Individualist', 'Individualist'), ('Competitive', 'Competitive')], max_length=10000, null=True)),
                ('inequality_aversion_score', otree.db.models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('paid_slider', otree.db.models.IntegerField(default=-1, null=True)),
                ('slider_as_receiver', otree.db.models.IntegerField(default=-1, null=True)),
                ('kept_of_sender', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('received_from_sender', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='svo.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_player', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('players_per_group', otree.db.models.IntegerField(null=True)),
                ('language', otree.db.models.StringField(choices=[('EN', 'EN'), ('DE', 'DE'), ('IT', 'IT')], max_length=10000, null=True)),
                ('select_items', otree.db.models.StringField(choices=[('PRIMARY', 'PRIMARY'), ('FULL', 'FULL')], max_length=10000, null=True)),
                ('items_in_random_order', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('scale', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('precision', otree.db.models.StringField(choices=[('INTEGERS', 'INTEGERS'), ('TWO_DIGITS_AFTER_POINT', 'TWO_DIGITS_AFTER_POINT')], max_length=10000, null=True)),
                ('matching', otree.db.models.StringField(choices=[('RING', 'RING'), ('RANDOM_DICTATOR', 'RANDOM_DICTATOR')], max_length=10000, null=True)),
                ('random_payoff', otree.db.models.StringField(choices=[('RAND', 'RAND'), ('SUM', 'SUM')], max_length=10000, null=True)),
                ('item_initialization', otree.db.models.StringField(choices=[('RAND', 'RAND'), ('AVG', 'AVG')], max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svo_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo.Subsession'),
        ),
    ]
