# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsession',
            name='item_initialization',
        ),
    ]
