# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 13:44
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('svo', '0002_remove_subsession_item_initialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsession',
            name='slider_init_type',
            field=otree.db.models.StringField(choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT'), ('RAND', 'RAND'), ('AVG', 'AVG')], max_length=10000, null=True),
        ),
    ]
