# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-06 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_de_group', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_de_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('input_self_1', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_1', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_2', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_2', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_3', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_3', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_4', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_4', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_5', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_5', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_6', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_6', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_7', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_7', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_8', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_8', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_9', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_9', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_10', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_10', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_11', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_11', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_12', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_12', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_13', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_13', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_14', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_14', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_self_15', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('input_other_15', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('random_order1', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order2', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order3', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order4', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order5', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order6', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order7', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order8', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order9', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order10', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order11', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order12', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order13', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order14', otree.db.models.IntegerField(default=-1, null=True)),
                ('random_order15', otree.db.models.IntegerField(default=-1, null=True)),
                ('svo_angle', otree.db.models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('svo_type', otree.db.models.StringField(choices=[('Altruist', 'Altruist'), ('Prosocial', 'Prosocial'), ('Individualist', 'Individualist'), ('Competitive', 'Competitive')], max_length=10000, null=True)),
                ('inequality_aversion_score', otree.db.models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('paid_slider', otree.db.models.IntegerField(default=-1, null=True)),
                ('slider_as_receiver', otree.db.models.IntegerField(default=-1, null=True)),
                ('kept_of_sender', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('received_from_sender', otree.db.models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('is_sender', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('is_receiver', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='svo_de.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_de_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svo_de_player', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_de_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('players_per_group', otree.db.models.IntegerField(null=True)),
                ('language', otree.db.models.StringField(choices=[('EN', 'EN'), ('DE', 'DE'), ('IT', 'IT'), ('FR', 'FR')], max_length=10000, null=True)),
                ('select_items', otree.db.models.StringField(choices=[('PRIMARY', 'PRIMARY'), ('FULL', 'FULL')], max_length=10000, null=True)),
                ('items_in_random_order', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('scale', otree.db.models.FloatField(null=True)),
                ('precision', otree.db.models.StringField(choices=[('INTEGERS', 'INTEGERS'), ('TWO_DIGITS_AFTER_POINT', 'TWO_DIGITS_AFTER_POINT')], max_length=10000, null=True)),
                ('matching', otree.db.models.StringField(choices=[('RING', 'RING'), ('RANDOM_DICTATOR', 'RANDOM_DICTATOR')], max_length=10000, null=True)),
                ('random_payoff', otree.db.models.StringField(choices=[('RAND', 'RAND'), ('SUM', 'SUM')], max_length=10000, null=True)),
                ('slider_init', otree.db.models.StringField(choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT'), ('RAND', 'RAND'), ('AVG', 'AVG')], max_length=10000, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='svo_de_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'svo_de_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo_de.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svo_de.Subsession'),
        ),
    ]
